name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiMzYxN2ExMDUtM2JjMy00MDljLWJkZjgtYWU0MzkzNGJiMDZmIiwidGVuYW50X2lkIjoiN2M2N2M1OWFhYWJjODg2NWM3NTlhYWM4MTM5ZmZiZDgyODZjZmNiMGE1ZTMxZDU1MDEyNGNkYmQ1ZjlmYzI0ZCIsImludGVybmFsX3NlY3JldCI6IjY5YTgyZjJiLWJhZjQtNDJjMi05OWE3LTQ1Nzc1MWM3NDEyNSJ9.moQItQ0hSs2dk8T0HluNGW6ErkcIwapcsiRDDd7tQyE"
JWT_SECRET="123455"